---
- hosts: myubuntuservers
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myResult

  - name: debug myResult
    debug:
      msg: "{{ myResult }}"
    


