---
- hosts: myubuntuservers
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: install webserver on ubuntu nodes 
    apt: 
     name: apache2
     state: present
    notify:  restartwebserver

  - name: start webserver on ubuntu nodes  
    service:
     name: apache2
     state: started

  - name: copy index.j2 file into all nodes sides
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify:  restartwebserver

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
