---
- hosts: myubuntuservers
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: install webserver on ubuntu nodes 
    apt: 
     name: apache2
     state: present
     
  - name: start webserver on ubuntu nodes  
    service:
     name: apache2
     state: started

   


