---
- hosts: all
  become: yes
  tasks:
  - name: install git
    apt:
     name: "{{item}}"
     state: present
    loop:
      - git
      - tree
      - wget
    when: ansible_os_family =="Debian"

