---
- name: deploy maha java application 
  get_url:
    url: https://mymaha6am.s3.us-east-2.amazonaws.com/mahaLogin.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes

- name: deploy jenkins java application 
  get_url:
    url:  https://get.jenkins.io/war-stable/2.263.2/jenkins.war
    dest: /opt/tomcat/webapps/jenkins.war
    force_basic_auth: yes
